language: cpp
sudo: required

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    
env:
    - CXX=g++-7
    
before_script:
  - cd src
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=g++-7
  
script:   
  - make

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
