language: cpp
sudo: required

compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    
env:
    - CXX=g++-7
    
before_script:
  - cd src
  - mkdir build
  - cd build
  - cmake ..
  
script:   make
