branches:
  only:
  - development
image: Visual Studio 2015
install:
before_build:
- cmd: >-
    cd C:\projects\depthcodec\src && mkdir build && cd build
    cmake ..
build:
    cmake --build
test_script:
  - ctest
