branches:
  only:
  - development
image: Visual Studio 2015
install:
before_build:
- cmd: >-
    cd c:\projects\depthcodec
    mkdir build && cd build
    cmake ..\src
build:
    cmake --build
test_script:
  - ctest
